version: '2'


networks:
    basic:


services:


# data layer

  data-cache:
    image: openjdk
    container_name: data-cache
    ports:
    - "9100:9100"
    environment: 
    - TZ=Asia/Shanghai
    volumes:
    - /jbh/servers/data/data-cache.jar:/jbh/data/application.jar:Z
    - /jbh/servers/data/data-cache.properties:/jbh/data/application.properties:Z
    - /jbh/servers/log/:/microservices/log/:Z
    command: java -jar /jbh/data/application.jar --spring.config.location=/jbh/data/application.properties >/dev/null 2>&1 & && tail -f /dev/null
    networks:
      - basic
    external_links:
    - eureka
    - zipkin
    - config
    - redis

  data-user:
    image: openjdk
    container_name: data-user
    ports:
    - "9101:9101"
    environment: 
    - TZ=Asia/Shanghai
    volumes:
    - /jbh/servers/data/data-user.jar:/jbh/data/application.jar:Z
    - /jbh/servers/data/data-user.properties:/jbh/data/application.properties:Z
    - /jbh/servers/log/:/microservices/log/:Z
    command: java -jar /jbh/data/application.jar --spring.config.location=/jbh/data/application.properties >/dev/null 2>&1 & && tail -f /dev/null
    networks:
      - basic
    external_links:
    - eureka
    - zipkin
    - config
    - mysql


 # middle platform layer

  mp-sms:
    image: openjdk
    container_name: mp-sms
    ports:
    - "9001:9001"
    environment: 
    - TZ=Asia/Shanghai
    volumes:
    - /jbh/servers/data/mp-sms.jar:/jbh/data/application.jar:Z
    - /jbh/servers/data/mp-sms.properties:/jbh/data/application.properties:Z
    - /jbh/servers/log/:/microservices/log/:Z
    command: java -jar /jbh/data/application.jar --spring.config.location=/jbh/data/application.properties >/dev/null 2>&1 & && tail -f /dev/null
    networks:
      - basic
    external_links:
    - eureka
    - zipkin
    - config

  mp-user:
    image: openjdk
    container_name: mp-user
    ports:
    - "9002:9002"
    environment: 
    - TZ=Asia/Shanghai
    volumes:
    - /jbh/servers/data/mp-user.jar:/jbh/data/application.jar:Z
    - /jbh/servers/data/mp-user.properties:/jbh/data/application.properties:Z
    - /jbh/servers/log/:/microservices/log/:Z
    command: java -jar /jbh/data/application.jar --spring.config.location=/jbh/data/application.properties >/dev/null 2>&1 & && tail -f /dev/null
    networks:
      - basic
    external_links:
    - eureka
    - zipkin
    - config



 # business layer

  jbh-biz-user:
    image: openjdk
    container_name: jbh-biz-user
    ports:
    - "8101:8101"
    environment: 
    - TZ=Asia/Shanghai
    volumes:
    - /jbh/servers/data/jbh-biz-user.jar:/jbh/data/application.jar:Z
    - /jbh/servers/data/jbh-biz-user.properties:/jbh/data/application.properties:Z
    - /jbh/servers/log/:/microservices/log/:Z
    command: java -jar /jbh/data/application.jar --spring.config.location=/jbh/data/application.properties >/dev/null 2>&1 & && tail -f /dev/null
    networks:
      - basic
    external_links:
    - eureka
    - zipkin
    - config



 # interfaces layer

  jbh-if-user:
    image: openjdk
    container_name: jbh-if-user
    ports:
    - "7101:7101"
    environment: 
    - TZ=Asia/Shanghai
    volumes:
    - /jbh/servers/data/jbh-if-user.jar:/jbh/data/application.jar:Z
    - /jbh/servers/data/jbh-if-user.properties:/jbh/data/application.properties:Z
    - /jbh/servers/log/:/microservices/log/:Z
    command: java -jar /jbh/data/application.jar --spring.config.location=/jbh/data/application.properties >/dev/null 2>&1 & && tail -f /dev/null
    networks:
      - basic
    external_links:
    - eureka
    - zipkin
    - config






 










